version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}

  build:
    commands:
      - echo Building PetClinic application...
      - echo Build started on `date`
      - docker build -t $ECR_REPO_APP:$IMAGE_TAG -f Dockerfile .
      - docker tag $ECR_REPO_APP:$IMAGE_TAG $ECR_REPO_APP:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO_APP:$IMAGE_TAG
      - docker push $ECR_REPO_APP:latest
      - echo Build completed on `date`
      - printf '{"ImageURI":"%s"}' $ECR_REPO_APP:$IMAGE_TAG > imageDetail.json

artifacts:
  files:
    - imageDetail.json
    - appspec.yml
    - taskdef.json
